server:
  port: 8080
  
spring:
  application:
    name: client-desk
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/swipepay
    username: client.desk
    password: D4b2W8Vdc6VAqzAY
    tomcat:
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-idle: 50
      suspect-timeout: 60
      time-between-eviction-runs-millis: 30000
      min-evictable-idle-time-millis: 60000
      validation-query: SELECT 1
      validation-interval: 30000
      remove-abandoned: true
      remove-abandoned-timeout: 60
      log-abandoned: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  thymeleaf:
    cache: false
    
management:
  context-path: /internal-management

# Here begins the client-desk specific properties.

client-desk:
  management:
    username-suffix: -management
    password: $2y$10$t0p94DqDuogk8JqBh2lZUeUPD.bxB1sZRMODbOa63Ri/pMeHIe9EW # p@ssw0rd (in bcrypt)

crypto-service-client:
  root-uri: http://localhost:8080
  connect-timeout: 15000 # 15 seconds
  read-timeout: 15000 # 15 seconds
  username: cryptoserviceauthuser
  password: cuXC=4!Kj2KD@3VT

